baseURL = "https://strongislands.netlify.app"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Contini"
#  English Config
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Contini](http://contini.com/) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
#  English Footer
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 5
[[Languages.en.menu.footer]]
URL = "https://www.lexpressproperty.com/en/"
name = "Services"
weight = 4
[[Languages.en.menu.footer]]
URL = "https://www.amazon.com"
name = "Products"
weight = 3
[[Languages.en.menu.footer]]
URL = "project"
name = "Projects"
weight = 2
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
# English Main menu
[[Languages.en.menu.main]]
URL = "https://www.amazon.com"
name = "Products"
parent = "Shop"
weight = 1
[[Languages.en.menu.main]]
URL = "https://www.lexpressproperty.com/en/"
name = "Services"
parent = "Shop"
weight = 2
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[Languages.en.menu.main]]
hasChildren = true
name = "Shop"
weight = 3
[[Languages.en.menu.main]]
URL = "project"
name = "Projects"
weight = 2
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 1
# French Config
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Contini](http://contini.com/) All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
#  French footer
[[Languages.fr.menu.footer]]
name = "À Propos"
URL = "about"
weight = 1

[[Languages.fr.menu.footer]]
name = "Projets"
URL = "project"
weight = 2

[[Languages.fr.menu.footer]]
name = "Produits"
URL = "https://www.amazon.fr/"
weight = 3

[[Languages.fr.menu.footer]]
name = "Services"
URL = "https://www.lexpressproperty.com/fr/"
weight = 4

[[Languages.fr.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6

# French Main menu
[[Languages.fr.menu.main]]
URL = "https://www.amazon.com"
name = "Produits"
parent = "Boutique"
weight = 1
[[Languages.fr.menu.main]]
URL = "https://www.lexpressproperty.com/en/"
name = "Services"
parent = "Boutique"
weight = 2
[[Languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[Languages.fr.menu.main]]
hasChildren = true
name = "Boutique"
weight = 3
[[Languages.fr.menu.main]]
URL = "project"
name = "Projets"
weight = 2
[[Languages.fr.menu.main]]
URL = "about"
name = "À propos"
weight = 1

[params]
author = "Nu!"
contact_form_action = "#"
description = "This is meta description"
email = "demo@email.com"
google_analitycs_id = ""
location = "Reunion Island, Indian Ocean"
logo = "/images/contini-logo2.png"
mobile = "0124857985320"
multi_author = false
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
